# Site settings
title: Latest Tech News
slogan: Ashley's Blog
username: Ashley Wang
email: swang2015@gmail.com
baseurl: ""
url: "http://ashleywang.me"
description: "I'm Ashley Wang, a Machine Learning Engineer and mother of two. I'm watching news about <b>data science, CV, NLU, robotics, quantum computing, innovative products</b>... and would like to share with you!"

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: swang2015