# Site settings
title: Latest Tech News
slogan: Ashley's Pick
username: Ashley Wang
email: swang2015@gmail.com
baseurl: ""
url: "http://ashleywang.me"
description: "I'm Ashley Wang, a machine learning engineer and mother of two. I'm reading latest technology news about <b>data science, foundation models, generative ai, physical ai, embodied ai, quantum computing, biomedical science, basic science, innovative products</b>... and would like to share with you!"

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 20f
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: swang2015