# Site settings
title: Tranquil
slogan: Ashley's Blog
username: Ashley Wang
email: swang2015@gmail.com
baseurl: ""
url: "http://ashleywang.me"
description: "A data scientist ❤️ machine learning, text mining, data visualization, natural language processing. A foodie, loves skiing and travelling."

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 3
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: swang2015