# Site settings
title: Latest Tech News
slogan: Ashley's Blog
username: Ashley Wang
email: swang2015@gmail.com
baseurl: ""
url: "http://ashleywang.me"
description: "A data scientist, foodie, <br> &#9829; snowboarding and travelling."

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "/page:num/"

# Comment thread setting
disqus_forumname: swang2015